<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNFgiXdo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNFgiXdo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNFgiXdo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNFgiXdo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNFgiXdo\App_KernelDevDebugContainer([
    'container.build_hash' => 'NFgiXdo',
    'container.build_id' => '430808b7',
    'container.build_time' => 1602501800,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNFgiXdo');
